# Generated by Django 6.0.5 on 2026-06-06 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_pedido_itempedido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_titular', models.CharField(max_length=100)),
                ('bandeira', models.CharField(max_length=20)),
                ('ultimos_digitos', models.CharField(max_length=4)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodos_pagamento', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
