# Generated by Django 6.0.5 on 2026-05-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_lojista',
            field=models.BooleanField(default=False),
        ),
    ]
